-- MySQL Script generated by MySQL Workbench
-- 01/01/17 19:30:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lab6
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab6` DEFAULT CHARACTER SET utf8 ;
USE `lab6` ;

-- -----------------------------------------------------
-- Table `lab6`.`classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab6`.`classroom` (
  `building` VARCHAR(15) NOT NULL DEFAULT '',
  `room_number` VARCHAR(7) NOT NULL DEFAULT '',
  `capacity` DECIMAL(4,0) NULL DEFAULT NULL,
  PRIMARY KEY (`building`, `room_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab6`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab6`.`department` (
  `dept_name` VARCHAR(20) NOT NULL DEFAULT '',
  `building_name` VARCHAR(15) NULL DEFAULT NULL,
  `budget` DECIMAL(12,2) NULL DEFAULT NULL,
  `dept_id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`dept_name`),
  UNIQUE INDEX `dept_id_UNIQUE` (`dept_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab6`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab6`.`course` (
  `course_id` VARCHAR(8) NOT NULL DEFAULT '',
  `title` VARCHAR(50) NULL DEFAULT NULL,
  `dept_name` VARCHAR(20) NULL DEFAULT NULL,
  `credits` DECIMAL(2,0) NULL DEFAULT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `dept_name` (`dept_name` ASC),
  CONSTRAINT `course_ibfk_1`
    FOREIGN KEY (`dept_name`)
    REFERENCES `lab6`.`department` (`dept_name`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab6`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab6`.`instructor` (
  `ID` VARCHAR(8) NOT NULL DEFAULT '',
  `name` VARCHAR(20) NOT NULL,
  `dept_name` VARCHAR(20) NULL DEFAULT NULL,
  `salary` DECIMAL(8,0) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `dept_name` (`dept_name` ASC),
  CONSTRAINT `instructor_ibfk_1`
    FOREIGN KEY (`dept_name`)
    REFERENCES `lab6`.`department` (`dept_name`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab6`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab6`.`section` (
  `course_id` VARCHAR(8) NOT NULL DEFAULT '',
  `sec_id` VARCHAR(28) NOT NULL DEFAULT '',
  `semester` VARCHAR(6) NOT NULL DEFAULT '',
  `year` DECIMAL(4,0) NOT NULL DEFAULT '0',
  `building` VARCHAR(15) NULL DEFAULT NULL,
  `room_number` VARCHAR(7) NULL DEFAULT NULL,
  `time_slot` VARCHAR(5) NULL DEFAULT NULL,
  `week` INT(11) NULL DEFAULT NULL,
  `week_slot` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`course_id`, `sec_id`, `semester`, `year`),
  INDEX `building` (`building` ASC, `room_number` ASC),
  CONSTRAINT `section_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `lab6`.`course` (`course_id`)
    ON DELETE CASCADE,
  CONSTRAINT `section_ibfk_2`
    FOREIGN KEY (`building` , `room_number`)
    REFERENCES `lab6`.`classroom` (`building` , `room_number`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab6`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab6`.`student` (
  `ID` VARCHAR(8) NOT NULL DEFAULT '',
  `name` VARCHAR(20) NOT NULL,
  `dept_name` VARCHAR(40) NULL DEFAULT NULL,
  `tot_cred` DECIMAL(3,0) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `dept_name` (`dept_name` ASC),
  CONSTRAINT `student_ibfk_1`
    FOREIGN KEY (`dept_name`)
    REFERENCES `lab6`.`department` (`dept_name`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab6`.`takes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab6`.`takes` (
  `ID` VARCHAR(8) NOT NULL DEFAULT '',
  `course_id` VARCHAR(8) NOT NULL DEFAULT '',
  `sec_id` VARCHAR(28) NOT NULL DEFAULT '',
  `semester` VARCHAR(6) NOT NULL DEFAULT '',
  `year` DECIMAL(4,0) NOT NULL DEFAULT '0',
  `grade` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`, `course_id`, `sec_id`, `semester`, `year`),
  INDEX `takes_ibfk_1` (`course_id` ASC, `sec_id` ASC, `semester` ASC, `year` ASC),
  CONSTRAINT `takes_ibfk_1`
    FOREIGN KEY (`course_id` , `sec_id` , `semester` , `year`)
    REFERENCES `lab6`.`section` (`course_id` , `sec_id` , `semester` , `year`)
    ON DELETE CASCADE,
  CONSTRAINT `takes_ibfk_2`
    FOREIGN KEY (`ID`)
    REFERENCES `lab6`.`student` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab6`.`teaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab6`.`teaches` (
  `ID` VARCHAR(8) NOT NULL DEFAULT '',
  `course_id` VARCHAR(8) NOT NULL DEFAULT '',
  `sec_id` VARCHAR(28) NOT NULL DEFAULT '',
  `semester` VARCHAR(6) NOT NULL DEFAULT '',
  `year` DECIMAL(4,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`, `course_id`, `sec_id`, `semester`, `year`),
  INDEX `teaches_ibfk_1` (`course_id` ASC, `sec_id` ASC, `semester` ASC, `year` ASC),
  CONSTRAINT `teaches_ibfk_1`
    FOREIGN KEY (`course_id` , `sec_id` , `semester` , `year`)
    REFERENCES `lab6`.`section` (`course_id` , `sec_id` , `semester` , `year`)
    ON DELETE CASCADE,
  CONSTRAINT `teaches_ibfk_2`
    FOREIGN KEY (`ID`)
    REFERENCES `lab6`.`instructor` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
